services:
  - type: web
    name: kinetix-api
    env: ruby
    plan: free
    buildCommand: "bundle install"
    startCommand: "rails server -p $PORT"
    envVars:
      - key: RAILS_ENV
        value: production

databases:
  - name: kinetix-db
    plan: free