default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: kinetix_live_development

test:
  <<: *default
  database: kinetix_live_test

# PRODUCTION: Use only DATABASE_URL from environment
production:
  url: <%= ENV['DATABASE_URL'] %>