services:
  - type: web
    name: kinetix-live
    env: ruby
    buildCommand: "./bin/render-build"
    startCommand: "bundle exec rails server -p $PORT"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false